#configuration file for ouputs
config={

    "SoC":{
        "SoC_1":{
            "position":1,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/SoC_1"
            }
        },
        "SoC_2":{
            "position":2,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/SoC_2"
            }
        },
        "SoC_3":{
            "position":3,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/SoC_3"
            }
        },
        "SoC_4":{
            "position":4,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/SoC_4"
            }
        }
    },
    "Sd":{
        "Sd_1":{
            "position":9,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/Sd_1"
            }
        },
        "Sd_2":{
            "position":10,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/Sd_2"
            }
        },
        "Sd_3":{
            "position":11,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/Sd_3"
            }
        },
        "Sd_4":{
            "position":12,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/Sd_4"
            }
        }
    },
    "Sc":{
        "Sc_1":{
            "position":5,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/Sc_1"
            }
        },
        "Sc_2":{
            "position":6,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/Sc_2"
            }
        },
        "Sc_3":{
            "position":7,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/Sc_3"
            }
        },
        "Sc_4":{
            "position":8,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/Sc_4"
            }
        }
    },
    "P_inv":{
        "P_inv_1":{
            "position":13,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/P_inv_1"
            }
        },
        "P_inv_2":{
            "position":14,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/P_inv_2"
            }
        },
        "P_inv_3":{
            "position":15,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/P_inv_3"
            }
        },
        "P_inv_4":{
            "position":16,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/P_inv_4"
            }
        }
    },
    "Q_inv":{
        "Q_inv_1":{
            "position":17,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/Q_inv_1"
            }
        },
        "Q_inv_2":{
            "position":18,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/Q_inv_2"
            }
        },
        "Q_inv_3":{
            "position":19,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/Q_inv_3"
            }
        },
        "Q_inv_4":{
            "position":20,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/Q_inv_4"
            }
        }
    },
    "V":{
        "V_1":{
            "position":21,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/V_1"
            }
        },
        "V_2":{
            "position":22,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/V_2"
            }
        },
        "V_3":{
            "position":23,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/V_3"
            }
        },
        "V_4":{
            "position":24,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/V_4"
            }
        }
    },
    "P_Load":{
        "P_Load_1":{
            "position":25,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/P_Load_1"
            }
        },
        "P_Load_2":{
            "position":26,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/P_Load_2"
            }
        },
        "P_Load_3":{
            "position":27,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/P_Load_3"
            }
        },
        "P_Load_4":{
            "position":28,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/P_Load_4"
            }
        }
    },
    "Q_Load":{
        "Q_Load_1":{
            "position":29,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/Q_Load_1"
            }
        },
        "Q_Load_2":{
            "position":30,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/Q_Load_2"
            }
        },
        "Q_Load_3":{
            "position":31,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/Q_Load_3"
            }
        },
        "Q_Load_4":{
            "position":32,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/Q_Load_4"
            }
        }
    },
    "P_PV":{
        "P_PV_1":{
            "position":33,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/P_PV_1"
            }
        },
        "P_PV_2":{
            "position":34,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/P_PV_2"
            }
        },
        "P_PV_3":{
            "position":35,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/P_PV_3"
            }
        },
        "P_PV_4":{
            "position":36,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/P_PV_4"
            }
        }
    },
    "Q_PV":{
        "Q_PV_1":{
            "position":37,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/Q_PV_1"
            }
        },
        "Q_PV_2":{
            "position":38,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/Q_PV_2"
            }
        },
        "Q_PV_3":{
            "position":39,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/Q_PV_3"
            }
        },
        "Q_PV_4":{
            "position":40,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/Q_PV_4"
            }
        }
    },
    "va":{
        "va_1":{
            "position":41,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/va_1"
            }
        },
        "va_2":{
            "position":42,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/va_2"
            }
        },
        "va_3":{
            "position":43,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/va_3"
            }
        },
        "va_4":{
            "position":44,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/va_4"
            }
        }
    },
    "BRKi":{
        "BRKi_1":{
            "position":45,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/BRKi_1"
            }
        },
        "BRKi_2":{
            "position":46,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/BRKi_2"
            }
        },
        "BRKi_3":{
            "position":47,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/BRKi_3"
            }
        },
        "BRKi_4":{
            "position":48,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/BRKi_4"
            }
        }
    },
    "m":{
        "m_1":{
            "position":49,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/m_1"
            }
        },
        "m_2":{
            "position":50,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/m_2"
            }
        },
        "m_3":{
            "position":51,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/m_3"
            }
        },
        "m_4":{
            "position":52,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/m_4"
            }
        }
    },
    "SoC_Ref":{
        "SoC_Ref_1":{
            "position":55,
            "mqtt":{
                "qos":1,
                "host":"192.168.99.100",
                "topic":"IST/SoC_Ref"
            }
        }
    }

}